apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-preprod-rollout-canary
  namespace: dev-preprod
spec:
  replicas: 3 # Número total de réplicas deseadas
  selector:
    matchLabels:
      app: dev-preprod
  template:
    metadata:
      labels:
        app: dev-preprod
    spec:
      containers:
      - name: dev-preprod
        image: docker.io/library/hello-world:latest # Nueva versión de la imagen
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dev-preprod-service
  namespace: dev-preprod
spec:
  selector:
    app: dev-preprod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
