apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-preprod-deployment
spec:
  replicas: 1 # Número de réplicas del pod
  selector:
    matchLabels:
      app: dev-preprod
  template:
    metadata:
      labels:
        app: dev-preprod
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: dev-preprod
        image: core.harbor.domain/mi-webapp/mi-webapp:1.0 # Nombre de la imagen de Docker
        ports:
        - containerPort: 80 # Puerto que expone el contenedor

---
apiVersion: v1
kind: Service
metadata:
  name: dev-preprod-service
spec:
  selector:
    app: dev-preprod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
